/* ============================================================
   data.js — squads, formations, position metadata
   Player obj: { n: name, p: positionCode, r: rating }
   Position codes: GK RB CB LB RWB LWB DM CM CAM RM LM RW LW ST CF
   ============================================================ */

/* ---- Position metadata: line (0 GK,1 DEF,2 MID,3 ATT) + side (L/C/R) ---- */
const POS_META = {
  GK:  { line: 0, side: 'C' },
  RB:  { line: 1, side: 'R' },
  CB:  { line: 1, side: 'C' },
  LB:  { line: 1, side: 'L' },
  RWB: { line: 1, side: 'R' },
  LWB: { line: 1, side: 'L' },
  DM:  { line: 2, side: 'C' },
  CM:  { line: 2, side: 'C' },
  CAM: { line: 2, side: 'C' },
  RM:  { line: 2, side: 'R' },
  LM:  { line: 2, side: 'L' },
  RW:  { line: 3, side: 'R' },
  LW:  { line: 3, side: 'L' },
  ST:  { line: 3, side: 'C' },
  CF:  { line: 3, side: 'C' },
};

/* ---- Formations: slots with role + pitch coords (x 0-100 L→R, y 7 GK → 84 ATT) ---- */
const FORMATIONS = {
  '4-3-3': [
    { role: 'GK',  x: 50, y: 7 },
    { role: 'RB',  x: 84, y: 26 }, { role: 'CB', x: 62, y: 21 }, { role: 'CB', x: 38, y: 21 }, { role: 'LB', x: 16, y: 26 },
    { role: 'CM',  x: 70, y: 46 }, { role: 'CM', x: 50, y: 50 }, { role: 'CM', x: 30, y: 46 },
    { role: 'RW',  x: 80, y: 72 }, { role: 'ST', x: 50, y: 80 }, { role: 'LW', x: 20, y: 72 },
  ],
  '4-4-2': [
    { role: 'GK',  x: 50, y: 7 },
    { role: 'RB',  x: 84, y: 26 }, { role: 'CB', x: 62, y: 21 }, { role: 'CB', x: 38, y: 21 }, { role: 'LB', x: 16, y: 26 },
    { role: 'RM',  x: 84, y: 52 }, { role: 'CM', x: 60, y: 48 }, { role: 'CM', x: 40, y: 48 }, { role: 'LM', x: 16, y: 52 },
    { role: 'ST',  x: 60, y: 80 }, { role: 'ST', x: 40, y: 80 },
  ],
  '4-2-3-1': [
    { role: 'GK',  x: 50, y: 7 },
    { role: 'RB',  x: 84, y: 26 }, { role: 'CB', x: 62, y: 21 }, { role: 'CB', x: 38, y: 21 }, { role: 'LB', x: 16, y: 26 },
    { role: 'DM',  x: 62, y: 40 }, { role: 'DM', x: 38, y: 40 },
    { role: 'RW',  x: 80, y: 64 }, { role: 'CAM', x: 50, y: 60 }, { role: 'LW', x: 20, y: 64 },
    { role: 'ST',  x: 50, y: 82 },
  ],
  '3-5-2': [
    { role: 'GK',  x: 50, y: 7 },
    { role: 'CB',  x: 70, y: 21 }, { role: 'CB', x: 50, y: 19 }, { role: 'CB', x: 30, y: 21 },
    { role: 'RWB', x: 88, y: 44 }, { role: 'CM', x: 64, y: 46 }, { role: 'CM', x: 50, y: 42 }, { role: 'CM', x: 36, y: 46 }, { role: 'LWB', x: 12, y: 44 },
    { role: 'ST',  x: 60, y: 80 }, { role: 'ST', x: 40, y: 80 },
  ],
  '5-3-2': [
    { role: 'GK',  x: 50, y: 7 },
    { role: 'RWB', x: 88, y: 28 }, { role: 'CB', x: 68, y: 21 }, { role: 'CB', x: 50, y: 19 }, { role: 'CB', x: 32, y: 21 }, { role: 'LWB', x: 12, y: 28 },
    { role: 'CM',  x: 68, y: 50 }, { role: 'CM', x: 50, y: 47 }, { role: 'CM', x: 32, y: 50 },
    { role: 'ST',  x: 60, y: 80 }, { role: 'ST', x: 40, y: 80 },
  ],
  '4-5-1': [
    { role: 'GK',  x: 50, y: 7 },
    { role: 'RB',  x: 84, y: 26 }, { role: 'CB', x: 62, y: 21 }, { role: 'CB', x: 38, y: 21 }, { role: 'LB', x: 16, y: 26 },
    { role: 'RM',  x: 86, y: 54 }, { role: 'CM', x: 66, y: 48 }, { role: 'CM', x: 50, y: 44 }, { role: 'CM', x: 34, y: 48 }, { role: 'LM', x: 14, y: 54 },
    { role: 'ST',  x: 50, y: 82 },
  ],
  '4-2-4': [
    { role: 'GK',  x: 50, y: 7 },
    { role: 'RB',  x: 84, y: 26 }, { role: 'CB', x: 62, y: 21 }, { role: 'CB', x: 38, y: 21 }, { role: 'LB', x: 16, y: 26 },
    { role: 'CM',  x: 62, y: 46 }, { role: 'CM', x: 38, y: 46 },
    { role: 'RW',  x: 84, y: 72 }, { role: 'ST', x: 60, y: 82 }, { role: 'ST', x: 40, y: 82 }, { role: 'LW', x: 16, y: 72 },
  ],
  '3-4-3': [
    { role: 'GK',  x: 50, y: 7 },
    { role: 'CB',  x: 70, y: 21 }, { role: 'CB', x: 50, y: 19 }, { role: 'CB', x: 30, y: 21 },
    { role: 'RM',  x: 84, y: 48 }, { role: 'CM', x: 60, y: 46 }, { role: 'CM', x: 40, y: 46 }, { role: 'LM', x: 16, y: 48 },
    { role: 'RW',  x: 80, y: 76 }, { role: 'ST', x: 50, y: 82 }, { role: 'LW', x: 20, y: 76 },
  ],
};

const STYLES = ['Defensive', 'Balanced', 'Attacking'];

/* ---- Squads ---- */
const SQUADS = [
  { country: 'Brazil', flag: '🇧🇷', year: 1970, players: [
    { n: 'Félix', p: 'GK', r: 80 }, { n: 'Carlos Alberto', p: 'RB', r: 90 }, { n: 'Brito', p: 'CB', r: 82 },
    { n: 'Piazza', p: 'CB', r: 83 }, { n: 'Everaldo', p: 'LB', r: 80 }, { n: 'Clodoaldo', p: 'DM', r: 85 },
    { n: 'Gérson', p: 'CM', r: 90 }, { n: 'Rivelino', p: 'CM', r: 92 }, { n: 'Jairzinho', p: 'RW', r: 91 },
    { n: 'Pelé', p: 'CAM', r: 99 }, { n: 'Tostão', p: 'ST', r: 89 }, { n: 'Edu', p: 'LW', r: 81 },
    { n: 'Paulo César', p: 'LW', r: 80 }, { n: 'Marco Antônio', p: 'LB', r: 79 }, { n: 'Fontana', p: 'CB', r: 78 },
    { n: 'Roberto', p: 'ST', r: 78 },
  ]},
  { country: 'Brazil', flag: '🇧🇷', year: 1982, players: [
    { n: 'Waldir Peres', p: 'GK', r: 78 }, { n: 'Leandro', p: 'RB', r: 85 }, { n: 'Oscar', p: 'CB', r: 82 },
    { n: 'Luizinho', p: 'CB', r: 80 }, { n: 'Júnior', p: 'LB', r: 86 }, { n: 'Falcão', p: 'CM', r: 91 },
    { n: 'Toninho Cerezo', p: 'DM', r: 84 }, { n: 'Sócrates', p: 'CAM', r: 93 }, { n: 'Zico', p: 'CAM', r: 94 },
    { n: 'Éder', p: 'LW', r: 86 }, { n: 'Serginho', p: 'ST', r: 79 }, { n: 'Careca', p: 'ST', r: 84 },
    { n: 'Paulo Isidoro', p: 'RW', r: 80 }, { n: 'Dirceu', p: 'CM', r: 81 }, { n: 'Edinho', p: 'CB', r: 80 },
    { n: 'Renato', p: 'GK', r: 75 },
  ]},
  { country: 'Brazil', flag: '🇧🇷', year: 1994, players: [
    { n: 'Taffarel', p: 'GK', r: 85 }, { n: 'Jorginho', p: 'RB', r: 82 }, { n: 'Aldair', p: 'CB', r: 86 },
    { n: 'Márcio Santos', p: 'CB', r: 81 }, { n: 'Branco', p: 'LB', r: 82 }, { n: 'Dunga', p: 'DM', r: 87 },
    { n: 'Mauro Silva', p: 'DM', r: 84 }, { n: 'Mazinho', p: 'CM', r: 80 }, { n: 'Bebeto', p: 'ST', r: 88 },
    { n: 'Romário', p: 'ST', r: 95 }, { n: 'Raí', p: 'CAM', r: 85 }, { n: 'Zinho', p: 'LM', r: 81 },
    { n: 'Cafu', p: 'RB', r: 86 }, { n: 'Leonardo', p: 'LB', r: 83 }, { n: 'Viola', p: 'ST', r: 79 },
    { n: 'Müller', p: 'RW', r: 80 },
  ]},
  { country: 'Brazil', flag: '🇧🇷', year: 2002, players: [
    { n: 'Marcos', p: 'GK', r: 83 }, { n: 'Cafu', p: 'RB', r: 88 }, { n: 'Lúcio', p: 'CB', r: 87 },
    { n: 'Roque Júnior', p: 'CB', r: 82 }, { n: 'Roberto Carlos', p: 'LB', r: 90 }, { n: 'Gilberto Silva', p: 'DM', r: 84 },
    { n: 'Kléberson', p: 'CM', r: 80 }, { n: 'Ronaldinho', p: 'CAM', r: 92 }, { n: 'Rivaldo', p: 'CAM', r: 93 },
    { n: 'Ronaldo', p: 'ST', r: 96 }, { n: 'Denílson', p: 'LW', r: 82 }, { n: 'Edmílson', p: 'CB', r: 81 },
    { n: 'Juninho', p: 'CM', r: 83 }, { n: 'Edílson', p: 'RW', r: 80 }, { n: 'Belletti', p: 'RB', r: 81 },
    { n: 'Júnior', p: 'LB', r: 79 },
  ]},
  { country: 'Argentina', flag: '🇦🇷', year: 1978, players: [
    { n: 'Ubaldo Fillol', p: 'GK', r: 86 }, { n: 'Jorge Olguín', p: 'RB', r: 80 }, { n: 'Luis Galván', p: 'CB', r: 81 },
    { n: 'Daniel Passarella', p: 'CB', r: 89 }, { n: 'Alberto Tarantini', p: 'LB', r: 82 }, { n: 'Osvaldo Ardiles', p: 'CM', r: 88 },
    { n: 'Américo Gallego', p: 'DM', r: 82 }, { n: 'Mario Kempes', p: 'ST', r: 91 }, { n: 'Daniel Bertoni', p: 'RW', r: 83 },
    { n: 'Leopoldo Luque', p: 'ST', r: 84 }, { n: 'René Houseman', p: 'RW', r: 82 }, { n: 'Ricardo Villa', p: 'CM', r: 80 },
    { n: 'Oscar Ortiz', p: 'LW', r: 79 }, { n: 'Norberto Alonso', p: 'CAM', r: 81 }, { n: 'Daniel Killer', p: 'CB', r: 77 },
    { n: 'Héctor Baley', p: 'GK', r: 74 },
  ]},
  { country: 'Argentina', flag: '🇦🇷', year: 1986, players: [
    { n: 'Nery Pumpido', p: 'GK', r: 81 }, { n: 'José Luis Cuciuffo', p: 'RB', r: 79 }, { n: 'José Luis Brown', p: 'CB', r: 82 },
    { n: 'Oscar Ruggeri', p: 'CB', r: 86 }, { n: 'Julio Olarticoechea', p: 'LB', r: 80 }, { n: 'Sergio Batista', p: 'DM', r: 81 },
    { n: 'Ricardo Giusti', p: 'CM', r: 81 }, { n: 'Héctor Enrique', p: 'CM', r: 80 }, { n: 'Jorge Burruchaga', p: 'CAM', r: 85 },
    { n: 'Diego Maradona', p: 'CAM', r: 98 }, { n: 'Jorge Valdano', p: 'ST', r: 86 }, { n: 'Pedro Pasculli', p: 'ST', r: 80 },
    { n: 'Claudio Borghi', p: 'RW', r: 80 }, { n: 'Nestor Clausen', p: 'RB', r: 77 }, { n: 'Oscar Garré', p: 'LB', r: 77 },
    { n: 'Daniel Passarella', p: 'CB', r: 85 },
  ]},
  { country: 'Argentina', flag: '🇦🇷', year: 2022, players: [
    { n: 'Emiliano Martínez', p: 'GK', r: 88 }, { n: 'Nahuel Molina', p: 'RB', r: 82 }, { n: 'Cristian Romero', p: 'CB', r: 86 },
    { n: 'Nicolás Otamendi', p: 'CB', r: 84 }, { n: 'Nicolás Tagliafico', p: 'LB', r: 82 }, { n: 'Rodrigo De Paul', p: 'CM', r: 85 },
    { n: 'Enzo Fernández', p: 'CM', r: 85 }, { n: 'Alexis Mac Allister', p: 'CM', r: 85 }, { n: 'Lionel Messi', p: 'CAM', r: 97 },
    { n: 'Julián Álvarez', p: 'ST', r: 86 }, { n: 'Ángel Di María', p: 'RW', r: 86 }, { n: 'Lautaro Martínez', p: 'ST', r: 85 },
    { n: 'Leandro Paredes', p: 'DM', r: 81 }, { n: 'Marcos Acuña', p: 'LB', r: 81 }, { n: 'Gonzalo Montiel', p: 'RB', r: 79 },
    { n: 'Lisandro Martínez', p: 'CB', r: 83 },
  ]},
  { country: 'France', flag: '🇫🇷', year: 1998, players: [
    { n: 'Fabien Barthez', p: 'GK', r: 85 }, { n: 'Lilian Thuram', p: 'RB', r: 88 }, { n: 'Marcel Desailly', p: 'CB', r: 88 },
    { n: 'Laurent Blanc', p: 'CB', r: 86 }, { n: 'Bixente Lizarazu', p: 'LB', r: 85 }, { n: 'Didier Deschamps', p: 'DM', r: 85 },
    { n: 'Emmanuel Petit', p: 'CM', r: 84 }, { n: 'Zinedine Zidane', p: 'CAM', r: 95 }, { n: 'Youri Djorkaeff', p: 'CAM', r: 86 },
    { n: 'Thierry Henry', p: 'ST', r: 88 }, { n: 'Stéphane Guivarc\'h', p: 'ST', r: 78 }, { n: 'Christophe Dugarry', p: 'ST', r: 80 },
    { n: 'David Trezeguet', p: 'ST', r: 84 }, { n: 'Robert Pirès', p: 'LW', r: 84 }, { n: 'Patrick Vieira', p: 'CM', r: 85 },
    { n: 'Christian Karembeu', p: 'CM', r: 80 },
  ]},
  { country: 'France', flag: '🇫🇷', year: 2018, players: [
    { n: 'Hugo Lloris', p: 'GK', r: 86 }, { n: 'Benjamin Pavard', p: 'RB', r: 82 }, { n: 'Raphaël Varane', p: 'CB', r: 87 },
    { n: 'Samuel Umtiti', p: 'CB', r: 84 }, { n: 'Lucas Hernández', p: 'LB', r: 83 }, { n: 'N\'Golo Kanté', p: 'DM', r: 89 },
    { n: 'Paul Pogba', p: 'CM', r: 88 }, { n: 'Blaise Matuidi', p: 'CM', r: 82 }, { n: 'Kylian Mbappé', p: 'RW', r: 91 },
    { n: 'Antoine Griezmann', p: 'CAM', r: 89 }, { n: 'Olivier Giroud', p: 'ST', r: 83 }, { n: 'Ousmane Dembélé', p: 'RW', r: 83 },
    { n: 'Corentin Tolisso', p: 'CM', r: 81 }, { n: 'Steven Nzonzi', p: 'DM', r: 80 }, { n: 'Benjamin Mendy', p: 'LB', r: 80 },
    { n: 'Thomas Lemar', p: 'LM', r: 81 },
  ]},
  { country: 'West Germany', flag: '🇩🇪', year: 1974, players: [
    { n: 'Sepp Maier', p: 'GK', r: 86 }, { n: 'Berti Vogts', p: 'RB', r: 84 }, { n: 'Franz Beckenbauer', p: 'CB', r: 94 },
    { n: 'Hans-Georg Schwarzenbeck', p: 'CB', r: 81 }, { n: 'Paul Breitner', p: 'LB', r: 87 }, { n: 'Uli Hoeneß', p: 'CM', r: 85 },
    { n: 'Wolfgang Overath', p: 'CM', r: 85 }, { n: 'Rainer Bonhof', p: 'DM', r: 83 }, { n: 'Jürgen Grabowski', p: 'RW', r: 83 },
    { n: 'Gerd Müller', p: 'ST', r: 92 }, { n: 'Bernd Hölzenbein', p: 'LW', r: 81 }, { n: 'Günter Netzer', p: 'CAM', r: 86 },
    { n: 'Heinz Flohe', p: 'CM', r: 79 }, { n: 'Dieter Herzog', p: 'LW', r: 77 }, { n: 'Horst-Dieter Höttges', p: 'RB', r: 78 },
    { n: 'Jupp Heynckes', p: 'ST', r: 82 },
  ]},
  { country: 'Germany', flag: '🇩🇪', year: 1990, players: [
    { n: 'Bodo Illgner', p: 'GK', r: 83 }, { n: 'Thomas Berthold', p: 'RB', r: 81 }, { n: 'Klaus Augenthaler', p: 'CB', r: 83 },
    { n: 'Jürgen Kohler', p: 'CB', r: 85 }, { n: 'Andreas Brehme', p: 'LB', r: 86 }, { n: 'Guido Buchwald', p: 'DM', r: 83 },
    { n: 'Lothar Matthäus', p: 'CM', r: 92 }, { n: 'Pierre Littbarski', p: 'RM', r: 83 }, { n: 'Thomas Häßler', p: 'CAM', r: 84 },
    { n: 'Rudi Völler', p: 'ST', r: 87 }, { n: 'Jürgen Klinsmann', p: 'ST', r: 88 }, { n: 'Olaf Thon', p: 'CM', r: 81 },
    { n: 'Stefan Reuter', p: 'RB', r: 80 }, { n: 'Uwe Bein', p: 'CAM', r: 80 }, { n: 'Karl-Heinz Riedle', p: 'ST', r: 81 },
    { n: 'Andreas Köpke', p: 'GK', r: 80 },
  ]},
  { country: 'Germany', flag: '🇩🇪', year: 2014, players: [
    { n: 'Manuel Neuer', p: 'GK', r: 92 }, { n: 'Philipp Lahm', p: 'RB', r: 89 }, { n: 'Jérôme Boateng', p: 'CB', r: 86 },
    { n: 'Mats Hummels', p: 'CB', r: 88 }, { n: 'Benedikt Höwedes', p: 'LB', r: 80 }, { n: 'Bastian Schweinsteiger', p: 'DM', r: 88 },
    { n: 'Sami Khedira', p: 'CM', r: 84 }, { n: 'Toni Kroos', p: 'CM', r: 89 }, { n: 'Thomas Müller', p: 'CAM', r: 88 },
    { n: 'Mesut Özil', p: 'CAM', r: 87 }, { n: 'Miroslav Klose', p: 'ST', r: 84 }, { n: 'Mario Götze', p: 'CAM', r: 84 },
    { n: 'André Schürrle', p: 'LW', r: 83 }, { n: 'Per Mertesacker', p: 'CB', r: 82 }, { n: 'Lukas Podolski', p: 'LW', r: 82 },
    { n: 'Julian Draxler', p: 'LM', r: 81 },
  ]},
  { country: 'Spain', flag: '🇪🇸', year: 2010, players: [
    { n: 'Iker Casillas', p: 'GK', r: 90 }, { n: 'Sergio Ramos', p: 'RB', r: 88 }, { n: 'Gerard Piqué', p: 'CB', r: 87 },
    { n: 'Carles Puyol', p: 'CB', r: 87 }, { n: 'Joan Capdevila', p: 'LB', r: 80 }, { n: 'Sergio Busquets', p: 'DM', r: 86 },
    { n: 'Xabi Alonso', p: 'CM', r: 87 }, { n: 'Xavi', p: 'CM', r: 92 }, { n: 'Andrés Iniesta', p: 'CAM', r: 92 },
    { n: 'David Villa', p: 'ST', r: 89 }, { n: 'Pedro', p: 'RW', r: 83 }, { n: 'Fernando Torres', p: 'ST', r: 85 },
    { n: 'Cesc Fàbregas', p: 'CM', r: 86 }, { n: 'David Silva', p: 'CAM', r: 87 }, { n: 'Carlos Marchena', p: 'CB', r: 80 },
    { n: 'Álvaro Arbeloa', p: 'RB', r: 80 },
  ]},
  { country: 'Italy', flag: '🇮🇹', year: 1982, players: [
    { n: 'Dino Zoff', p: 'GK', r: 88 }, { n: 'Claudio Gentile', p: 'RB', r: 85 }, { n: 'Gaetano Scirea', p: 'CB', r: 88 },
    { n: 'Fulvio Collovati', p: 'CB', r: 81 }, { n: 'Antonio Cabrini', p: 'LB', r: 84 }, { n: 'Gabriele Oriali', p: 'DM', r: 81 },
    { n: 'Marco Tardelli', p: 'CM', r: 86 }, { n: 'Giancarlo Antognoni', p: 'CAM', r: 85 }, { n: 'Bruno Conti', p: 'RW', r: 85 },
    { n: 'Paolo Rossi', p: 'ST', r: 89 }, { n: 'Francesco Graziani', p: 'ST', r: 81 }, { n: 'Giuseppe Bergomi', p: 'CB', r: 82 },
    { n: 'Franco Causio', p: 'RM', r: 80 }, { n: 'Alessandro Altobelli', p: 'ST', r: 82 }, { n: 'Giuseppe Dossena', p: 'CM', r: 78 },
    { n: 'Ivano Bordon', p: 'GK', r: 76 },
  ]},
  { country: 'Italy', flag: '🇮🇹', year: 2006, players: [
    { n: 'Gianluigi Buffon', p: 'GK', r: 92 }, { n: 'Gianluca Zambrotta', p: 'RB', r: 85 }, { n: 'Fabio Cannavaro', p: 'CB', r: 90 },
    { n: 'Marco Materazzi', p: 'CB', r: 83 }, { n: 'Fabio Grosso', p: 'LB', r: 82 }, { n: 'Andrea Pirlo', p: 'DM', r: 90 },
    { n: 'Gennaro Gattuso', p: 'CM', r: 84 }, { n: 'Daniele De Rossi', p: 'CM', r: 84 }, { n: 'Francesco Totti', p: 'CAM', r: 89 },
    { n: 'Luca Toni', p: 'ST', r: 84 }, { n: 'Alberto Gilardino', p: 'ST', r: 82 }, { n: 'Mauro Camoranesi', p: 'RM', r: 82 },
    { n: 'Alessandro Del Piero', p: 'CAM', r: 86 }, { n: 'Simone Perrotta', p: 'CM', r: 81 }, { n: 'Massimo Oddo', p: 'RB', r: 78 },
    { n: 'Alessandro Nesta', p: 'CB', r: 87 },
  ]},
  { country: 'Netherlands', flag: '🇳🇱', year: 1974, players: [
    { n: 'Jan Jongbloed', p: 'GK', r: 78 }, { n: 'Wim Suurbier', p: 'RB', r: 82 }, { n: 'Wim Rijsbergen', p: 'CB', r: 80 },
    { n: 'Arie Haan', p: 'CB', r: 84 }, { n: 'Ruud Krol', p: 'LB', r: 86 }, { n: 'Wim van Hanegem', p: 'CM', r: 87 },
    { n: 'Johan Neeskens', p: 'CM', r: 88 }, { n: 'Johan Cruyff', p: 'CAM', r: 96 }, { n: 'Johnny Rep', p: 'RW', r: 84 },
    { n: 'Rob Rensenbrink', p: 'LW', r: 85 }, { n: 'Piet Keizer', p: 'LW', r: 82 }, { n: 'René van de Kerkhof', p: 'RM', r: 80 },
    { n: 'Willy van de Kerkhof', p: 'DM', r: 80 }, { n: 'Theo de Jong', p: 'CM', r: 78 }, { n: 'Pleun Strik', p: 'CM', r: 76 },
    { n: 'Piet Schrijvers', p: 'GK', r: 76 },
  ]},
  { country: 'Netherlands', flag: '🇳🇱', year: 2010, players: [
    { n: 'Maarten Stekelenburg', p: 'GK', r: 83 }, { n: 'Gregory van der Wiel', p: 'RB', r: 81 }, { n: 'John Heitinga', p: 'CB', r: 82 },
    { n: 'Joris Mathijsen', p: 'CB', r: 81 }, { n: 'Giovanni van Bronckhorst', p: 'LB', r: 84 }, { n: 'Mark van Bommel', p: 'DM', r: 84 },
    { n: 'Nigel de Jong', p: 'DM', r: 83 }, { n: 'Wesley Sneijder', p: 'CAM', r: 89 }, { n: 'Arjen Robben', p: 'RW', r: 90 },
    { n: 'Robin van Persie', p: 'ST', r: 88 }, { n: 'Dirk Kuyt', p: 'LW', r: 82 }, { n: 'Rafael van der Vaart', p: 'CAM', r: 84 },
    { n: 'Klaas-Jan Huntelaar', p: 'ST', r: 83 }, { n: 'Eljero Elia', p: 'LW', r: 79 }, { n: 'Demy de Zeeuw', p: 'CM', r: 79 },
    { n: 'Khalid Boulahrouz', p: 'CB', r: 78 },
  ]},
  { country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', year: 1966, players: [
    { n: 'Gordon Banks', p: 'GK', r: 88 }, { n: 'George Cohen', p: 'RB', r: 81 }, { n: 'Jack Charlton', p: 'CB', r: 83 },
    { n: 'Bobby Moore', p: 'CB', r: 90 }, { n: 'Ray Wilson', p: 'LB', r: 82 }, { n: 'Nobby Stiles', p: 'DM', r: 81 },
    { n: 'Alan Ball', p: 'CM', r: 84 }, { n: 'Bobby Charlton', p: 'CAM', r: 91 }, { n: 'Martin Peters', p: 'CM', r: 83 },
    { n: 'Geoff Hurst', p: 'ST', r: 86 }, { n: 'Roger Hunt', p: 'ST', r: 82 }, { n: 'Jimmy Greaves', p: 'ST', r: 86 },
    { n: 'Ian Callaghan', p: 'RM', r: 79 }, { n: 'Terry Paine', p: 'RW', r: 78 }, { n: 'George Eastham', p: 'CM', r: 78 },
    { n: 'Ron Springett', p: 'GK', r: 75 },
  ]},
  { country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', year: 2018, players: [
    { n: 'Jordan Pickford', p: 'GK', r: 82 }, { n: 'Kyle Walker', p: 'RB', r: 84 }, { n: 'John Stones', p: 'CB', r: 83 },
    { n: 'Harry Maguire', p: 'CB', r: 82 }, { n: 'Kieran Trippier', p: 'RB', r: 82 }, { n: 'Ashley Young', p: 'LB', r: 79 },
    { n: 'Jordan Henderson', p: 'DM', r: 82 }, { n: 'Jesse Lingard', p: 'CM', r: 80 }, { n: 'Dele Alli', p: 'CAM', r: 82 },
    { n: 'Harry Kane', p: 'ST', r: 89 }, { n: 'Raheem Sterling', p: 'RW', r: 85 }, { n: 'Marcus Rashford', p: 'LW', r: 83 },
    { n: 'Eric Dier', p: 'DM', r: 80 }, { n: 'Jamie Vardy', p: 'ST', r: 82 }, { n: 'Fabian Delph', p: 'LB', r: 78 },
    { n: 'Trippier', p: 'RB', r: 81 },
  ]},
  { country: 'Portugal', flag: '🇵🇹', year: 2018, players: [
    { n: 'Rui Patrício', p: 'GK', r: 84 }, { n: 'Cédric Soares', p: 'RB', r: 80 }, { n: 'Pepe', p: 'CB', r: 84 },
    { n: 'José Fonte', p: 'CB', r: 80 }, { n: 'Raphaël Guerreiro', p: 'LB', r: 83 }, { n: 'William Carvalho', p: 'DM', r: 82 },
    { n: 'João Moutinho', p: 'CM', r: 83 }, { n: 'Bernardo Silva', p: 'CAM', r: 86 }, { n: 'João Mário', p: 'CM', r: 80 },
    { n: 'Cristiano Ronaldo', p: 'ST', r: 93 }, { n: 'Gonçalo Guedes', p: 'LW', r: 81 }, { n: 'André Silva', p: 'ST', r: 80 },
    { n: 'Ricardo Quaresma', p: 'RW', r: 81 }, { n: 'Bruno Fernandes', p: 'CAM', r: 83 }, { n: 'Adrien Silva', p: 'CM', r: 79 },
    { n: 'Mário Rui', p: 'LB', r: 78 },
  ]},
  { country: 'Uruguay', flag: '🇺🇾', year: 1950, players: [
    { n: 'Roque Máspoli', p: 'GK', r: 82 }, { n: 'Matías González', p: 'RB', r: 79 }, { n: 'Eusebio Tejera', p: 'CB', r: 80 },
    { n: 'Obdulio Varela', p: 'CB', r: 88 }, { n: 'Schubert Gambetta', p: 'LB', r: 78 }, { n: 'Víctor Andrade', p: 'DM', r: 80 },
    { n: 'Rodríguez Andrade', p: 'CM', r: 81 }, { n: 'Juan Alberto Schiaffino', p: 'CAM', r: 89 }, { n: 'Alcides Ghiggia', p: 'RW', r: 85 },
    { n: 'Óscar Míguez', p: 'ST', r: 84 }, { n: 'Julio Pérez', p: 'LW', r: 80 }, { n: 'Ernesto Vidal', p: 'RW', r: 79 },
    { n: 'Rubén Morán', p: 'LW', r: 77 }, { n: 'William Martínez', p: 'RB', r: 76 }, { n: 'Luis Cruz', p: 'CB', r: 76 },
    { n: 'Aníbal Paz', p: 'GK', r: 75 },
  ]},
  { country: 'Croatia', flag: '🇭🇷', year: 2018, players: [
    { n: 'Danijel Subašić', p: 'GK', r: 82 }, { n: 'Šime Vrsaljko', p: 'RB', r: 81 }, { n: 'Dejan Lovren', p: 'CB', r: 82 },
    { n: 'Domagoj Vida', p: 'CB', r: 81 }, { n: 'Ivan Strinić', p: 'LB', r: 78 }, { n: 'Marcelo Brozović', p: 'DM', r: 83 },
    { n: 'Luka Modrić', p: 'CM', r: 91 }, { n: 'Ivan Rakitić', p: 'CM', r: 86 }, { n: 'Ante Rebić', p: 'RW', r: 81 },
    { n: 'Mario Mandžukić', p: 'ST', r: 84 }, { n: 'Ivan Perišić', p: 'LW', r: 84 }, { n: 'Andrej Kramarić', p: 'ST', r: 81 },
    { n: 'Marko Pjaca', p: 'LW', r: 78 }, { n: 'Mateo Kovačić', p: 'CM', r: 82 }, { n: 'Milan Badelj', p: 'DM', r: 79 },
    { n: 'Lovre Kalinić', p: 'GK', r: 76 },
  ]},
  { country: 'Belgium', flag: '🇧🇪', year: 2018, players: [
    { n: 'Thibaut Courtois', p: 'GK', r: 89 }, { n: 'Toby Alderweireld', p: 'CB', r: 86 }, { n: 'Vincent Kompany', p: 'CB', r: 85 },
    { n: 'Jan Vertonghen', p: 'CB', r: 84 }, { n: 'Thomas Meunier', p: 'RB', r: 81 }, { n: 'Yannick Carrasco', p: 'LB', r: 82 },
    { n: 'Axel Witsel', p: 'DM', r: 84 }, { n: 'Kevin De Bruyne', p: 'CM', r: 92 }, { n: 'Eden Hazard', p: 'CAM', r: 91 },
    { n: 'Romelu Lukaku', p: 'ST', r: 87 }, { n: 'Dries Mertens', p: 'RW', r: 84 }, { n: 'Marouane Fellaini', p: 'CM', r: 81 },
    { n: 'Nacer Chadli', p: 'LM', r: 80 }, { n: 'Mousa Dembélé', p: 'DM', r: 82 }, { n: 'Youri Tielemans', p: 'CM', r: 80 },
    { n: 'Michy Batshuayi', p: 'ST', r: 80 },
  ]},
  { country: 'Hungary', flag: '🇭🇺', year: 1954, players: [
    { n: 'Gyula Grosics', p: 'GK', r: 85 }, { n: 'Jenő Buzánszky', p: 'RB', r: 80 }, { n: 'Gyula Lóránt', p: 'CB', r: 82 },
    { n: 'Mihály Lantos', p: 'LB', r: 80 }, { n: 'József Bozsik', p: 'CM', r: 87 }, { n: 'József Zakariás', p: 'DM', r: 80 },
    { n: 'Nándor Hidegkuti', p: 'CAM', r: 88 }, { n: 'Sándor Kocsis', p: 'ST', r: 90 }, { n: 'Ferenc Puskás', p: 'CAM', r: 94 },
    { n: 'Zoltán Czibor', p: 'LW', r: 84 }, { n: 'László Budai', p: 'RW', r: 81 }, { n: 'Mihály Tóth', p: 'LW', r: 78 },
    { n: 'Péter Palotás', p: 'ST', r: 80 }, { n: 'Gyula Tóth', p: 'CB', r: 76 }, { n: 'Ferenc Szojka', p: 'CM', r: 77 },
    { n: 'Sándor Gellér', p: 'GK', r: 74 },
  ]},
  { country: 'Colombia', flag: '🇨🇴', year: 2014, players: [
    { n: 'David Ospina', p: 'GK', r: 83 }, { n: 'Juan Zúñiga', p: 'RB', r: 80 }, { n: 'Mario Yepes', p: 'CB', r: 81 },
    { n: 'Cristián Zapata', p: 'CB', r: 80 }, { n: 'Pablo Armero', p: 'LB', r: 80 }, { n: 'Carlos Sánchez', p: 'DM', r: 81 },
    { n: 'Abel Aguilar', p: 'CM', r: 79 }, { n: 'James Rodríguez', p: 'CAM', r: 89 }, { n: 'Juan Cuadrado', p: 'RW', r: 84 },
    { n: 'Teófilo Gutiérrez', p: 'ST', r: 81 }, { n: 'Jackson Martínez', p: 'ST', r: 83 }, { n: 'Víctor Ibarbo', p: 'LW', r: 79 },
    { n: 'Carlos Bacca', p: 'ST', r: 82 }, { n: 'Fredy Guarín', p: 'CM', r: 81 }, { n: 'Juan Quintero', p: 'CAM', r: 80 },
    { n: 'Camilo Zúñiga', p: 'RB', r: 78 },
  ]},
  { country: 'Brazil', flag: '🇧🇷', year: 2026, players: [
    { n: 'Alisson', p: 'GK', r: 89 }, { n: 'Danilo', p: 'RB', r: 81 }, { n: 'Marquinhos', p: 'CB', r: 87 },
    { n: 'Gabriel Magalhães', p: 'CB', r: 85 }, { n: 'Wendell', p: 'LB', r: 80 }, { n: 'Bruno Guimarães', p: 'DM', r: 86 },
    { n: 'Casemiro', p: 'DM', r: 84 }, { n: 'Lucas Paquetá', p: 'CM', r: 83 }, { n: 'Vinícius Júnior', p: 'LW', r: 90 },
    { n: 'Rodrygo', p: 'RW', r: 86 }, { n: 'Raphinha', p: 'RW', r: 86 }, { n: 'Endrick', p: 'ST', r: 83 },
    { n: 'Estêvão', p: 'RW', r: 83 }, { n: 'João Pedro', p: 'ST', r: 82 }, { n: 'Éderson', p: 'GK', r: 85 },
    { n: 'Andreas Pereira', p: 'CM', r: 80 },
  ]},
  { country: 'France', flag: '🇫🇷', year: 2026, players: [
    { n: 'Mike Maignan', p: 'GK', r: 87 }, { n: 'Jules Koundé', p: 'RB', r: 85 }, { n: 'William Saliba', p: 'CB', r: 87 },
    { n: 'Dayot Upamecano', p: 'CB', r: 84 }, { n: 'Theo Hernández', p: 'LB', r: 84 }, { n: 'Aurélien Tchouaméni', p: 'DM', r: 86 },
    { n: 'Eduardo Camavinga', p: 'CM', r: 85 }, { n: 'Antoine Griezmann', p: 'CAM', r: 87 }, { n: 'Kylian Mbappé', p: 'ST', r: 94 },
    { n: 'Ousmane Dembélé', p: 'RW', r: 87 }, { n: 'Bradley Barcola', p: 'LW', r: 83 }, { n: 'Marcus Thuram', p: 'ST', r: 84 },
    { n: 'Warren Zaïre-Emery', p: 'CM', r: 82 }, { n: 'Michael Olise', p: 'RW', r: 85 }, { n: 'Ibrahima Konaté', p: 'CB', r: 83 },
    { n: 'N\'Golo Kanté', p: 'DM', r: 83 },
  ]},
  { country: 'Brazil', flag: '🇧🇷', year: 1958, players: [
    { n: 'Gilmar', p: 'GK', r: 88 }, { n: 'Djalma Santos', p: 'RB', r: 89 }, { n: 'Nílton Santos', p: 'LB', r: 90 },
    { n: 'Bellini', p: 'CB', r: 85 }, { n: 'Orlando', p: 'CB', r: 83 }, { n: 'Zito', p: 'DM', r: 85 },
    { n: 'Didi', p: 'CM', r: 92 }, { n: 'Garrincha', p: 'RW', r: 95 }, { n: 'Mário Zagallo', p: 'LW', r: 86 },
    { n: 'Pelé', p: 'CF', r: 97 }, { n: 'Vavá', p: 'ST', r: 86 }, { n: 'Mazzola', p: 'ST', r: 82 },
    { n: 'Pepe', p: 'LW', r: 82 }, { n: 'Dida', p: 'CM', r: 79 }, { n: 'Joel', p: 'CM', r: 77 },
    { n: 'De Sordi', p: 'RB', r: 80 },
  ]},
  { country: 'Brazil', flag: '🇧🇷', year: 2006, players: [
    { n: 'Dida', p: 'GK', r: 84 }, { n: 'Cafu', p: 'RB', r: 86 }, { n: 'Roberto Carlos', p: 'LB', r: 88 },
    { n: 'Lúcio', p: 'CB', r: 87 }, { n: 'Juan', p: 'CB', r: 83 }, { n: 'Gilberto Silva', p: 'DM', r: 84 },
    { n: 'Emerson', p: 'DM', r: 83 }, { n: 'Kaká', p: 'CAM', r: 92 }, { n: 'Ronaldinho', p: 'CAM', r: 95 },
    { n: 'Ronaldo', p: 'ST', r: 88 }, { n: 'Adriano', p: 'ST', r: 86 }, { n: 'Robinho', p: 'LW', r: 83 },
    { n: 'Juninho Pernambucano', p: 'CM', r: 83 }, { n: 'Zé Roberto', p: 'LM', r: 82 }, { n: 'Cicinho', p: 'RB', r: 79 },
    { n: 'Fred', p: 'ST', r: 77 },
  ]},
  { country: 'Argentina', flag: '🇦🇷', year: 2014, players: [
    { n: 'Sergio Romero', p: 'GK', r: 82 }, { n: 'Pablo Zabaleta', p: 'RB', r: 85 }, { n: 'Marcos Rojo', p: 'LB', r: 81 },
    { n: 'Ezequiel Garay', p: 'CB', r: 84 }, { n: 'Federico Fernández', p: 'CB', r: 80 }, { n: 'Martín Demichelis', p: 'CB', r: 80 },
    { n: 'Javier Mascherano', p: 'DM', r: 89 }, { n: 'Lucas Biglia', p: 'CM', r: 80 }, { n: 'Ángel Di María', p: 'RW', r: 88 },
    { n: 'Lionel Messi', p: 'CAM', r: 97 }, { n: 'Sergio Agüero', p: 'ST', r: 89 }, { n: 'Gonzalo Higuaín', p: 'ST', r: 86 },
    { n: 'Ezequiel Lavezzi', p: 'LW', r: 82 }, { n: 'Maxi Rodríguez', p: 'RM', r: 79 }, { n: 'Fernando Gago', p: 'CM', r: 80 },
    { n: 'Rodrigo Palacio', p: 'ST', r: 80 },
  ]},
  { country: 'Germany', flag: '🇩🇪', year: 2006, players: [
    { n: 'Jens Lehmann', p: 'GK', r: 85 }, { n: 'Philipp Lahm', p: 'LB', r: 85 }, { n: 'Arne Friedrich', p: 'RB', r: 80 },
    { n: 'Per Mertesacker', p: 'CB', r: 82 }, { n: 'Christoph Metzelder', p: 'CB', r: 81 }, { n: 'Michael Ballack', p: 'CM', r: 90 },
    { n: 'Torsten Frings', p: 'DM', r: 83 }, { n: 'Bernd Schneider', p: 'RM', r: 81 }, { n: 'Bastian Schweinsteiger', p: 'CM', r: 82 },
    { n: 'Tim Borowski', p: 'CM', r: 78 }, { n: 'Miroslav Klose', p: 'ST', r: 87 }, { n: 'Lukas Podolski', p: 'LW', r: 84 },
    { n: 'Oliver Neuville', p: 'ST', r: 79 }, { n: 'David Odonkor', p: 'RM', r: 76 }, { n: 'Sebastian Kehl', p: 'DM', r: 78 },
    { n: 'Marcell Jansen', p: 'LB', r: 76 },
  ]},
  { country: 'France', flag: '🇫🇷', year: 2006, players: [
    { n: 'Fabien Barthez', p: 'GK', r: 83 }, { n: 'Lilian Thuram', p: 'RB', r: 86 }, { n: 'Willy Sagnol', p: 'RB', r: 82 },
    { n: 'William Gallas', p: 'CB', r: 84 }, { n: 'Éric Abidal', p: 'LB', r: 82 }, { n: 'Patrick Vieira', p: 'CM', r: 88 },
    { n: 'Claude Makélélé', p: 'DM', r: 87 }, { n: 'Zinedine Zidane', p: 'CAM', r: 93 }, { n: 'Florent Malouda', p: 'LW', r: 82 },
    { n: 'Franck Ribéry', p: 'RW', r: 83 }, { n: 'Thierry Henry', p: 'ST', r: 91 }, { n: 'David Trezeguet', p: 'ST', r: 84 },
    { n: 'Sylvain Wiltord', p: 'ST', r: 80 }, { n: 'Vikash Dhorasoo', p: 'CM', r: 77 }, { n: 'Alou Diarra', p: 'DM', r: 77 },
    { n: 'Gaël Clichy', p: 'LB', r: 76 },
  ]},
  { country: 'France', flag: '🇫🇷', year: 1986, players: [
    { n: 'Joël Bats', p: 'GK', r: 81 }, { n: 'Manuel Amoros', p: 'RB', r: 84 }, { n: 'Maxime Bossis', p: 'CB', r: 83 },
    { n: 'Patrick Battiston', p: 'CB', r: 82 }, { n: 'Yvon Le Roux', p: 'CB', r: 79 }, { n: 'Michel Platini', p: 'CAM', r: 93 },
    { n: 'Alain Giresse', p: 'CM', r: 86 }, { n: 'Jean Tigana', p: 'CM', r: 86 }, { n: 'Luis Fernández', p: 'DM', r: 83 },
    { n: 'Dominique Rocheteau', p: 'RW', r: 82 }, { n: 'Jean-Pierre Papin', p: 'ST', r: 83 }, { n: 'Yannick Stopyra', p: 'ST', r: 80 },
    { n: 'Bruno Bellone', p: 'LW', r: 78 }, { n: 'Jean-Marc Ferreri', p: 'RM', r: 77 }, { n: 'Thierry Tusseau', p: 'LB', r: 76 },
    { n: 'William Ayache', p: 'RB', r: 76 },
  ]},
  { country: 'Italy', flag: '🇮🇹', year: 1994, players: [
    { n: 'Gianluca Pagliuca', p: 'GK', r: 84 }, { n: 'Mauro Tassotti', p: 'RB', r: 82 }, { n: 'Paolo Maldini', p: 'LB', r: 90 },
    { n: 'Franco Baresi', p: 'CB', r: 90 }, { n: 'Alessandro Costacurta', p: 'CB', r: 85 }, { n: 'Antonio Benarrivo', p: 'LB', r: 78 },
    { n: 'Demetrio Albertini', p: 'CM', r: 85 }, { n: 'Dino Baggio', p: 'CM', r: 83 }, { n: 'Nicola Berti', p: 'CM', r: 80 },
    { n: 'Roberto Donadoni', p: 'RM', r: 84 }, { n: 'Roberto Baggio', p: 'CAM', r: 93 }, { n: 'Giuseppe Signori', p: 'ST', r: 84 },
    { n: 'Daniele Massaro', p: 'ST', r: 81 }, { n: 'Pierluigi Casiraghi', p: 'ST', r: 80 }, { n: 'Gianfranco Zola', p: 'CF', r: 84 },
    { n: 'Antonio Conte', p: 'CM', r: 79 },
  ]},
  { country: 'Italy', flag: '🇮🇹', year: 1990, players: [
    { n: 'Walter Zenga', p: 'GK', r: 85 }, { n: 'Franco Baresi', p: 'CB', r: 90 }, { n: 'Paolo Maldini', p: 'LB', r: 87 },
    { n: 'Riccardo Ferri', p: 'CB', r: 81 }, { n: 'Giuseppe Bergomi', p: 'RB', r: 84 }, { n: 'Roberto Donadoni', p: 'RM', r: 84 },
    { n: 'Giuseppe Giannini', p: 'CAM', r: 84 }, { n: 'Fernando De Napoli', p: 'CM', r: 80 }, { n: 'Carlo Ancelotti', p: 'CM', r: 81 },
    { n: 'Nicola Berti', p: 'CM', r: 80 }, { n: 'Roberto Baggio', p: 'CF', r: 88 }, { n: 'Salvatore Schillaci', p: 'ST', r: 86 },
    { n: 'Gianluca Vialli', p: 'ST', r: 85 }, { n: 'Andrea Carnevale', p: 'ST', r: 78 }, { n: 'Roberto Mancini', p: 'CF', r: 82 },
    { n: 'Stefano Tacconi', p: 'GK', r: 78 },
  ]},
  { country: 'Netherlands', flag: '🇳🇱', year: 1998, players: [
    { n: 'Edwin van der Sar', p: 'GK', r: 87 }, { n: 'Frank de Boer', p: 'CB', r: 86 }, { n: 'Jaap Stam', p: 'CB', r: 87 },
    { n: 'Michael Reiziger', p: 'RB', r: 82 }, { n: 'Arthur Numan', p: 'LB', r: 81 }, { n: 'Edgar Davids', p: 'DM', r: 87 },
    { n: 'Phillip Cocu', p: 'CM', r: 84 }, { n: 'Clarence Seedorf', p: 'CM', r: 85 }, { n: 'Ronald de Boer', p: 'CAM', r: 82 },
    { n: 'Marc Overmars', p: 'LW', r: 86 }, { n: 'Dennis Bergkamp', p: 'CF', r: 91 }, { n: 'Patrick Kluivert', p: 'ST', r: 86 },
    { n: 'Boudewijn Zenden', p: 'RW', r: 80 }, { n: 'Pierre van Hooijdonk', p: 'ST', r: 80 }, { n: 'Wim Jonk', p: 'CM', r: 79 },
    { n: 'Jimmy Floyd Hasselbaink', p: 'ST', r: 81 },
  ]},
  { country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', year: 1990, players: [
    { n: 'Peter Shilton', p: 'GK', r: 85 }, { n: 'Stuart Pearce', p: 'LB', r: 84 }, { n: 'Des Walker', p: 'CB', r: 83 },
    { n: 'Terry Butcher', p: 'CB', r: 82 }, { n: 'Paul Parker', p: 'RB', r: 79 }, { n: 'Mark Wright', p: 'CB', r: 80 },
    { n: 'Paul Gascoigne', p: 'CAM', r: 88 }, { n: 'David Platt', p: 'CM', r: 84 }, { n: 'Bryan Robson', p: 'CM', r: 84 },
    { n: 'Chris Waddle', p: 'LW', r: 84 }, { n: 'John Barnes', p: 'LW', r: 85 }, { n: 'Gary Lineker', p: 'ST', r: 88 },
    { n: 'Peter Beardsley', p: 'CF', r: 83 }, { n: 'Trevor Steven', p: 'RM', r: 79 }, { n: 'Steve McMahon', p: 'CM', r: 78 },
    { n: 'David Seaman', p: 'GK', r: 80 },
  ]},
  { country: 'Portugal', flag: '🇵🇹', year: 2006, players: [
    { n: 'Ricardo', p: 'GK', r: 82 }, { n: 'Miguel', p: 'RB', r: 80 }, { n: 'Ricardo Carvalho', p: 'CB', r: 87 },
    { n: 'Fernando Meira', p: 'CB', r: 80 }, { n: 'Nuno Valente', p: 'LB', r: 78 }, { n: 'Maniche', p: 'CM', r: 84 },
    { n: 'Costinha', p: 'DM', r: 81 }, { n: 'Deco', p: 'CAM', r: 88 }, { n: 'Luís Figo', p: 'RW', r: 87 },
    { n: 'Cristiano Ronaldo', p: 'LW', r: 86 }, { n: 'Pauleta', p: 'ST', r: 83 }, { n: 'Simão Sabrosa', p: 'LW', r: 82 },
    { n: 'Tiago', p: 'CM', r: 80 }, { n: 'Hélder Postiga', p: 'ST', r: 78 }, { n: 'Petit', p: 'DM', r: 78 },
    { n: 'Nuno Gomes', p: 'ST', r: 80 },
  ]},
  { country: 'Uruguay', flag: '🇺🇾', year: 2010, players: [
    { n: 'Fernando Muslera', p: 'GK', r: 82 }, { n: 'Diego Lugano', p: 'CB', r: 82 }, { n: 'Diego Godín', p: 'CB', r: 84 },
    { n: 'Jorge Fucile', p: 'RB', r: 79 }, { n: 'Maximiliano Pereira', p: 'RB', r: 81 }, { n: 'Álvaro Pereira', p: 'LB', r: 80 },
    { n: 'Diego Pérez', p: 'DM', r: 80 }, { n: 'Egidio Arévalo Ríos', p: 'DM', r: 80 }, { n: 'Walter Gargano', p: 'CM', r: 79 },
    { n: 'Nicolás Lodeiro', p: 'CM', r: 78 }, { n: 'Diego Forlán', p: 'ST', r: 89 }, { n: 'Luis Suárez', p: 'ST', r: 85 },
    { n: 'Edinson Cavani', p: 'ST', r: 83 }, { n: 'Sebastián Abreu', p: 'ST', r: 77 }, { n: 'Martín Cáceres', p: 'CB', r: 79 },
    { n: 'Ignacio González', p: 'CM', r: 76 },
  ]},
  { country: 'Mexico', flag: '🇲🇽', year: 1986, players: [
    { n: 'Pablo Larios', p: 'GK', r: 82 }, { n: 'Fernando Quirarte', p: 'CB', r: 81 }, { n: 'Mario Trejo', p: 'CB', r: 78 },
    { n: 'Armando Manzo', p: 'CB', r: 77 }, { n: 'Carlos Hermosillo', p: 'ST', r: 81 }, { n: 'Tomás Boy', p: 'CM', r: 82 },
    { n: 'Miguel España', p: 'DM', r: 78 }, { n: 'Javier Aguirre', p: 'CM', r: 79 }, { n: 'Manuel Negrete', p: 'CAM', r: 83 },
    { n: 'Raúl Servín', p: 'RB', r: 76 }, { n: 'Hugo Sánchez', p: 'ST', r: 89 }, { n: 'Luis Flores', p: 'ST', r: 80 },
    { n: 'Francisco Javier Cruz', p: 'ST', r: 78 }, { n: 'Carlos de los Cobos', p: 'LM', r: 77 }, { n: 'Rafael Amador', p: 'LB', r: 75 },
    { n: 'Félix Cruz', p: 'RB', r: 75 },
  ]},
  { country: 'USA', flag: '🇺🇸', year: 2002, players: [
    { n: 'Brad Friedel', p: 'GK', r: 84 }, { n: 'Eddie Pope', p: 'CB', r: 80 }, { n: 'Tony Sanneh', p: 'RB', r: 79 },
    { n: 'Gregg Berhalter', p: 'CB', r: 77 }, { n: 'Jeff Agoos', p: 'CB', r: 77 }, { n: 'Frankie Hejduk', p: 'RB', r: 77 },
    { n: 'Claudio Reyna', p: 'CM', r: 83 }, { n: 'John O\'Brien', p: 'CM', r: 80 }, { n: 'Pablo Mastroeni', p: 'DM', r: 77 },
    { n: 'DaMarcus Beasley', p: 'LM', r: 80 }, { n: 'Landon Donovan', p: 'CAM', r: 82 }, { n: 'Brian McBride', p: 'ST', r: 81 },
    { n: 'Clint Mathis', p: 'ST', r: 78 }, { n: 'Earnie Stewart', p: 'RM', r: 78 }, { n: 'Eddie Lewis', p: 'LM', r: 76 },
    { n: 'Kasey Keller', p: 'GK', r: 82 },
  ]},
  { country: 'South Korea', flag: '🇰🇷', year: 2002, players: [
    { n: 'Lee Woon-jae', p: 'GK', r: 81 }, { n: 'Hong Myung-bo', p: 'CB', r: 84 }, { n: 'Choi Jin-cheul', p: 'CB', r: 79 },
    { n: 'Kim Tae-young', p: 'CB', r: 78 }, { n: 'Lee Young-pyo', p: 'LB', r: 81 }, { n: 'Song Chong-gug', p: 'RB', r: 78 },
    { n: 'Yoo Sang-chul', p: 'CM', r: 80 }, { n: 'Kim Nam-il', p: 'DM', r: 80 }, { n: 'Park Ji-sung', p: 'CM', r: 83 },
    { n: 'Lee Chun-soo', p: 'LW', r: 79 }, { n: 'Seol Ki-hyeon', p: 'RW', r: 80 }, { n: 'Ahn Jung-hwan', p: 'ST', r: 81 },
    { n: 'Hwang Sun-hong', p: 'ST', r: 79 }, { n: 'Choi Yong-soo', p: 'ST', r: 77 }, { n: 'Yoon Jong-hwan', p: 'CAM', r: 77 },
    { n: 'Cha Du-ri', p: 'RM', r: 76 },
  ]},
  { country: 'Ghana', flag: '🇬🇭', year: 2010, players: [
    { n: 'Richard Kingson', p: 'GK', r: 79 }, { n: 'John Mensah', p: 'CB', r: 81 }, { n: 'John Pantsil', p: 'RB', r: 78 },
    { n: 'Isaac Vorsah', p: 'CB', r: 78 }, { n: 'Hans Sarpei', p: 'LB', r: 77 }, { n: 'Samuel Inkoom', p: 'RB', r: 76 },
    { n: 'Michael Essien', p: 'CM', r: 86 }, { n: 'Sulley Muntari', p: 'CM', r: 82 }, { n: 'Kwadwo Asamoah', p: 'CM', r: 80 },
    { n: 'Anthony Annan', p: 'DM', r: 79 }, { n: 'Kevin-Prince Boateng', p: 'CAM', r: 81 }, { n: 'André Ayew', p: 'LW', r: 79 },
    { n: 'Asamoah Gyan', p: 'ST', r: 83 }, { n: 'Prince Tagoe', p: 'ST', r: 76 }, { n: 'Stephen Appiah', p: 'CM', r: 79 },
    { n: 'Matthew Amoah', p: 'ST', r: 75 },
  ]},
  { country: 'Nigeria', flag: '🇳🇬', year: 1994, players: [
    { n: 'Peter Rufai', p: 'GK', r: 81 }, { n: 'Stephen Keshi', p: 'CB', r: 80 }, { n: 'Uche Okechukwu', p: 'CB', r: 79 },
    { n: 'Augustine Eguavoen', p: 'RB', r: 78 }, { n: 'Benedict Iroha', p: 'LB', r: 78 }, { n: 'Sunday Oliseh', p: 'DM', r: 83 },
    { n: 'Jay-Jay Okocha', p: 'CAM', r: 85 }, { n: 'Finidi George', p: 'RW', r: 83 }, { n: 'Emmanuel Amunike', p: 'LW', r: 83 },
    { n: 'Mutiu Adepoju', p: 'CM', r: 78 }, { n: 'Rashidi Yekini', p: 'ST', r: 85 }, { n: 'Daniel Amokachi', p: 'ST', r: 83 },
    { n: 'Samson Siasia', p: 'ST', r: 78 }, { n: 'Victor Ikpeba', p: 'ST', r: 80 }, { n: 'Efan Ekoku', p: 'ST', r: 78 },
    { n: 'Thompson Oliha', p: 'DM', r: 76 },
  ]},
  { country: 'Cameroon', flag: '🇨🇲', year: 1990, players: [
    { n: 'Thomas N\'Kono', p: 'GK', r: 83 }, { n: 'Stephen Tataw', p: 'RB', r: 78 }, { n: 'Benjamin Massing', p: 'CB', r: 77 },
    { n: 'Bertin Ebwellé', p: 'CB', r: 76 }, { n: 'Victor Ndip', p: 'LB', r: 76 }, { n: 'Emmanuel Kundé', p: 'CB', r: 80 },
    { n: 'André Kana-Biyik', p: 'DM', r: 78 }, { n: 'Cyrille Makanaky', p: 'CAM', r: 80 }, { n: 'Emile Mbouh', p: 'CM', r: 77 },
    { n: 'Louis-Paul Mfédé', p: 'CM', r: 78 }, { n: 'François Omam-Biyik', p: 'ST', r: 83 }, { n: 'Roger Milla', p: 'ST', r: 86 },
    { n: 'Eugène Ekéké', p: 'ST', r: 78 }, { n: 'Roger Feutmba', p: 'RM', r: 75 }, { n: 'Joseph-Antoine Bell', p: 'GK', r: 79 },
    { n: 'Thomas Libiih', p: 'CB', r: 75 },
  ]},
  { country: 'Morocco', flag: '🇲🇦', year: 2022, players: [
    { n: 'Yassine Bounou', p: 'GK', r: 85 }, { n: 'Achraf Hakimi', p: 'RB', r: 86 }, { n: 'Noussair Mazraoui', p: 'LB', r: 82 },
    { n: 'Romain Saïss', p: 'CB', r: 81 }, { n: 'Nayef Aguerd', p: 'CB', r: 82 }, { n: 'Jawad El Yamiq', p: 'CB', r: 78 },
    { n: 'Yahya Attiyat Allah', p: 'LB', r: 77 }, { n: 'Sofyan Amrabat', p: 'DM', r: 85 }, { n: 'Azzedine Ounahi', p: 'CM', r: 81 },
    { n: 'Selim Amallah', p: 'CM', r: 78 }, { n: 'Hakim Ziyech', p: 'RW', r: 84 }, { n: 'Sofiane Boufal', p: 'LW', r: 81 },
    { n: 'Youssef En-Nesyri', p: 'ST', r: 82 }, { n: 'Abderrazak Hamdallah', p: 'ST', r: 78 }, { n: 'Zakaria Aboukhlal', p: 'RW', r: 78 },
    { n: 'Abdelhamid Sabiri', p: 'CAM', r: 77 },
  ]},
  { country: 'Brazil', flag: '🇧🇷', year: 2014, players: [
    { n: 'Júlio César', p: 'GK', r: 82 }, { n: 'Dani Alves', p: 'RB', r: 84 }, { n: 'Thiago Silva', p: 'CB', r: 87 },
    { n: 'David Luiz', p: 'CB', r: 83 }, { n: 'Marcelo', p: 'LB', r: 85 }, { n: 'Maicon', p: 'RB', r: 80 },
    { n: 'Luiz Gustavo', p: 'DM', r: 81 }, { n: 'Fernandinho', p: 'CM', r: 82 }, { n: 'Paulinho', p: 'CM', r: 79 },
    { n: 'Oscar', p: 'CAM', r: 83 }, { n: 'Neymar', p: 'LW', r: 88 }, { n: 'Hulk', p: 'RW', r: 81 },
    { n: 'Fred', p: 'ST', r: 78 }, { n: 'Willian', p: 'RW', r: 80 }, { n: 'Ramires', p: 'CM', r: 79 },
    { n: 'Bernard', p: 'LW', r: 77 },
  ]},
  { country: 'Argentina', flag: '🇦🇷', year: 1990, players: [
    { n: 'Sergio Goycochea', p: 'GK', r: 84 }, { n: 'Oscar Ruggeri', p: 'CB', r: 84 }, { n: 'Juan Simón', p: 'CB', r: 78 },
    { n: 'Roberto Sensini', p: 'CB', r: 79 }, { n: 'Julio Olarticoechea', p: 'LB', r: 79 }, { n: 'José Basualdo', p: 'CM', r: 79 },
    { n: 'Sergio Batista', p: 'DM', r: 80 }, { n: 'Pedro Troglio', p: 'CM', r: 77 }, { n: 'Jorge Burruchaga', p: 'CAM', r: 83 },
    { n: 'Diego Maradona', p: 'CAM', r: 94 }, { n: 'Claudio Caniggia', p: 'ST', r: 84 }, { n: 'Gustavo Dezotti', p: 'ST', r: 77 },
    { n: 'Abel Balbo', p: 'ST', r: 79 }, { n: 'Néstor Lorenzo', p: 'CB', r: 76 }, { n: 'Pedro Monzón', p: 'LB', r: 76 },
    { n: 'Nery Pumpido', p: 'GK', r: 79 },
  ]},

  /* ===== Classic vintage squads (1950s–1970s) ===== */
  { country: 'Italy', flag: '🇮🇹', year: 1970, players: [
    { n: 'Enrico Albertosi', p: 'GK', r: 85 }, { n: 'Tarcisio Burgnich', p: 'RB', r: 84 }, { n: 'Pierluigi Cera', p: 'CB', r: 81 },
    { n: 'Roberto Rosato', p: 'CB', r: 80 }, { n: 'Giacinto Facchetti', p: 'LB', r: 88 }, { n: 'Mario Bertini', p: 'DM', r: 80 },
    { n: 'Giancarlo De Sisti', p: 'CM', r: 83 }, { n: 'Sandro Mazzola', p: 'CM', r: 87 }, { n: 'Gianni Rivera', p: 'CAM', r: 88 },
    { n: 'Angelo Domenghini', p: 'RW', r: 82 }, { n: 'Gigi Riva', p: 'ST', r: 90 }, { n: 'Roberto Boninsegna', p: 'ST', r: 84 },
    { n: 'Dino Zoff', p: 'GK', r: 84 }, { n: 'Comunardo Niccolai', p: 'CB', r: 76 }, { n: 'Giuseppe Furino', p: 'CM', r: 78 },
    { n: 'Gianni Rivera II', p: 'ST', r: 77 },
  ]},
  { country: 'West Germany', flag: '🇩🇪', year: 1970, players: [
    { n: 'Sepp Maier', p: 'GK', r: 86 }, { n: 'Berti Vogts', p: 'RB', r: 84 }, { n: 'Karl-Heinz Schnellinger', p: 'CB', r: 83 },
    { n: 'Franz Beckenbauer', p: 'CB', r: 92 }, { n: 'Horst-Dieter Höttges', p: 'LB', r: 79 }, { n: 'Klaus Fichtel', p: 'DM', r: 80 },
    { n: 'Wolfgang Overath', p: 'CM', r: 86 }, { n: 'Jürgen Grabowski', p: 'RW', r: 82 }, { n: 'Uwe Seeler', p: 'ST', r: 86 },
    { n: 'Gerd Müller', p: 'ST', r: 93 }, { n: 'Sigfried Held', p: 'LW', r: 82 }, { n: 'Reinhard Libuda', p: 'RW', r: 81 },
    { n: 'Hannes Löhr', p: 'LW', r: 80 }, { n: 'Wolfgang Weber', p: 'CB', r: 79 }, { n: 'Willi Schulz', p: 'CB', r: 80 },
    { n: 'Horst Wolter', p: 'GK', r: 74 },
  ]},
  { country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', year: 1970, players: [
    { n: 'Gordon Banks', p: 'GK', r: 89 }, { n: 'Tommy Wright', p: 'RB', r: 79 }, { n: 'Brian Labone', p: 'CB', r: 81 },
    { n: 'Bobby Moore', p: 'CB', r: 90 }, { n: 'Terry Cooper', p: 'LB', r: 80 }, { n: 'Alan Mullery', p: 'DM', r: 82 },
    { n: 'Alan Ball', p: 'CM', r: 84 }, { n: 'Bobby Charlton', p: 'CM', r: 88 }, { n: 'Francis Lee', p: 'RW', r: 82 },
    { n: 'Geoff Hurst', p: 'ST', r: 85 }, { n: 'Martin Peters', p: 'LW', r: 84 }, { n: 'Peter Bonetti', p: 'GK', r: 80 },
    { n: 'Norman Hunter', p: 'CB', r: 81 }, { n: 'Colin Bell', p: 'CM', r: 83 }, { n: 'Jeff Astle', p: 'ST', r: 79 },
    { n: 'Keith Newton', p: 'RB', r: 78 },
  ]},
  { country: 'Poland', flag: '🇵🇱', year: 1974, players: [
    { n: 'Jan Tomaszewski', p: 'GK', r: 86 }, { n: 'Antoni Szymanowski', p: 'RB', r: 80 }, { n: 'Jerzy Gorgoń', p: 'CB', r: 83 },
    { n: 'Władysław Żmuda', p: 'CB', r: 84 }, { n: 'Adam Musiał', p: 'LB', r: 80 }, { n: 'Henryk Maszczyk', p: 'DM', r: 79 },
    { n: 'Henryk Kasperczak', p: 'CM', r: 81 }, { n: 'Kazimierz Deyna', p: 'CAM', r: 90 }, { n: 'Grzegorz Lato', p: 'RW', r: 89 },
    { n: 'Andrzej Szarmach', p: 'ST', r: 86 }, { n: 'Robert Gadocha', p: 'LW', r: 84 }, { n: 'Lesław Ćmikiewicz', p: 'CM', r: 78 },
    { n: 'Jan Domarski', p: 'ST', r: 80 }, { n: 'Kazimierz Kmiecik', p: 'ST', r: 79 }, { n: 'Zygmunt Maszczyk', p: 'CB', r: 76 },
    { n: 'Zdzisław Kapka', p: 'CM', r: 77 },
  ]},
  { country: 'Netherlands', flag: '🇳🇱', year: 1978, players: [
    { n: 'Jan Jongbloed', p: 'GK', r: 79 }, { n: 'Wim Suurbier', p: 'RB', r: 80 }, { n: 'Ruud Krol', p: 'CB', r: 88 },
    { n: 'Wim Rijsbergen', p: 'CB', r: 80 }, { n: 'Jan Poortvliet', p: 'LB', r: 79 }, { n: 'Ernie Brandts', p: 'CB', r: 81 },
    { n: 'Wim Jansen', p: 'DM', r: 84 }, { n: 'Johan Neeskens', p: 'CM', r: 88 }, { n: 'Arie Haan', p: 'CM', r: 85 },
    { n: 'Willy van de Kerkhof', p: 'RM', r: 81 }, { n: 'René van de Kerkhof', p: 'LM', r: 81 }, { n: 'Johnny Rep', p: 'RW', r: 85 },
    { n: 'Rob Rensenbrink', p: 'LW', r: 87 }, { n: 'Dick Nanninga', p: 'ST', r: 80 }, { n: 'Piet Schrijvers', p: 'GK', r: 75 },
    { n: 'Pieter Wildschut', p: 'LW', r: 77 },
  ]},
  { country: 'Peru', flag: '🇵🇪', year: 1978, players: [
    { n: 'Ramón Quiroga', p: 'GK', r: 81 }, { n: 'Jaime Duarte', p: 'RB', r: 78 }, { n: 'Héctor Chumpitaz', p: 'CB', r: 84 },
    { n: 'Toribio Díaz', p: 'CB', r: 78 }, { n: 'Rodulfo Manzo', p: 'LB', r: 78 }, { n: 'José Velásquez', p: 'DM', r: 80 },
    { n: 'César Cueto', p: 'CM', r: 82 }, { n: 'Teófilo Cubillas', p: 'CAM', r: 90 }, { n: 'Juan Muñante', p: 'RW', r: 82 },
    { n: 'Juan Carlos Oblitas', p: 'LW', r: 83 }, { n: 'Guillermo La Rosa', p: 'ST', r: 78 }, { n: 'Hugo Sotil', p: 'ST', r: 82 },
    { n: 'Germán Leguía', p: 'CM', r: 78 }, { n: 'Rubén Toribio Díaz', p: 'RB', r: 77 }, { n: 'Ottorino Sartor', p: 'GK', r: 74 },
    { n: 'Percy Rojas', p: 'LW', r: 78 },
  ]},
  { country: 'Italy', flag: '🇮🇹', year: 1978, players: [
    { n: 'Dino Zoff', p: 'GK', r: 87 }, { n: 'Antonio Cuccureddu', p: 'RB', r: 79 }, { n: 'Claudio Gentile', p: 'CB', r: 84 },
    { n: 'Gaetano Scirea', p: 'CB', r: 86 }, { n: 'Antonio Cabrini', p: 'LB', r: 83 }, { n: 'Romeo Benetti', p: 'DM', r: 81 },
    { n: 'Marco Tardelli', p: 'CM', r: 84 }, { n: 'Giancarlo Antognoni', p: 'CAM', r: 84 }, { n: 'Franco Causio', p: 'RW', r: 83 },
    { n: 'Paolo Rossi', p: 'ST', r: 86 }, { n: 'Roberto Bettega', p: 'LW', r: 85 }, { n: 'Mauro Bellugi', p: 'CB', r: 79 },
    { n: 'Francesco Graziani', p: 'ST', r: 82 }, { n: 'Aldo Maldera', p: 'LB', r: 79 }, { n: 'Renato Zaccarelli', p: 'CM', r: 79 },
    { n: 'Ivano Bordon', p: 'GK', r: 75 },
  ]},
  { country: 'France', flag: '🇫🇷', year: 1958, players: [
    { n: 'Claude Abbes', p: 'GK', r: 78 }, { n: 'Raymond Kaelbel', p: 'RB', r: 79 }, { n: 'Robert Jonquet', p: 'CB', r: 83 },
    { n: 'Jean-Jacques Marcel', p: 'CB', r: 80 }, { n: 'André Lerond', p: 'LB', r: 78 }, { n: 'Armand Penverne', p: 'DM', r: 80 },
    { n: 'Raymond Kopa', p: 'CAM', r: 89 }, { n: 'Roger Piantoni', p: 'CM', r: 84 }, { n: 'Maryan Wisnieski', p: 'RW', r: 81 },
    { n: 'Just Fontaine', p: 'ST', r: 91 }, { n: 'Jean Vincent', p: 'LW', r: 81 }, { n: 'Yvon Douis', p: 'CM', r: 79 },
    { n: 'Thadée Cisowski', p: 'ST', r: 78 }, { n: 'Robert Siatka', p: 'CB', r: 76 }, { n: 'François Remetter', p: 'GK', r: 75 },
    { n: 'Stéphane Bruey', p: 'LW', r: 76 },
  ]},
  { country: 'Soviet Union', flag: '🇷🇺', year: 1966, players: [
    { n: 'Lev Yashin', p: 'GK', r: 90 }, { n: 'Vladimir Ponomaryov', p: 'RB', r: 78 }, { n: 'Albert Shesternyov', p: 'CB', r: 82 },
    { n: 'Murtaz Khurtsilava', p: 'CB', r: 79 }, { n: 'Valentin Afonin', p: 'LB', r: 78 }, { n: 'Valery Voronin', p: 'DM', r: 83 },
    { n: 'Yozhef Sabo', p: 'CM', r: 80 }, { n: 'Igor Chislenko', p: 'RW', r: 82 }, { n: 'Anatoliy Banishevskiy', p: 'ST', r: 81 },
    { n: 'Eduard Malofeyev', p: 'ST', r: 80 }, { n: 'Valeriy Porkujan', p: 'LW', r: 80 }, { n: 'Slava Metreveli', p: 'RW', r: 81 },
    { n: 'Galimzyan Khusainov', p: 'LW', r: 79 }, { n: 'Georgi Sichinava', p: 'CM', r: 77 }, { n: 'Vasily Danilov', p: 'LB', r: 77 },
    { n: 'Anzor Kavazashvili', p: 'GK', r: 76 },
  ]},
];

const WC_YEARS = [...new Set(SQUADS.map(s => s.year))].sort((a, b) => a - b);
